# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb703051a6f55fa2909149a088ea182ac034e1094e0b334c1b896b314930e075639f4201689d90ef52fb7a888e18422d4e94e977146b86e4cc86d7c8adf48967

test:
  secret_key_base: 775923d3305dc9d74d8e583c3bd41abf5d00244884a7317c066ac8f6fcbdf819f59a14329fa30ef8c827e6b19ab43bc8da9725498dddf0f16f6f618dfd06ca8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
